### ISSUE TITLE
Minimal viable application template for reproducing bug reports

### ISSUE THREAD

**Issue by jarosluv** [hanami/hanami#786]
Hi, folks!

I propose to add a one-file minimal Hanami application for reproducing errors and other similar things. We have a good [example in Rails world](https://github.com/rails/rails/tree/master/guides/bug_report_templates).

The first attempt for implement this looks like that: https://gist.github.com/jarosluv/508c2ececd32d3e4afe788b569846776

The main problem is if we uncomment commented lines we will get errors. And for now I don't know how to fix this.

**Comment by cllns** [comment]
I like this idea! The example you show would be good for `hanami/model`. Each library would have their own (including `hanami/hanami`)

**Comment by jodosha** [comment]
@jarosluv Hi, that is a neat idea. Are you interested to make it to happen?

**Comment by jarosluv** [comment]
@jodosha 

Yes, of course! I use this draft in another issues and it's very useful.
Please, give me some ideas how to improve this templates and I can start to work further.

**Comment by davydovanton** [comment]
I want to create a simple todo list for the future coordination. Also, I created a simple template  for model with sqlite.

## TODO

- [ ] hanami full app
- [ ] hanami model with sqlite adapter
- [ ] hanami model with postgresql adapter
- [ ] hanami model with msql adapter
- [ ] hanami controller
- [ ] hanami view
- [ ] hanami view with helpers
- [ ] hanami interactor
- [ ] hanami mailer

**Comment by jodosha** [comment]
Closing in favor of https://github.com/hanami/playbook/issues/2
